export enum RuntimeMessage {
  CONVERT_TO_PDF_OPEN_MODAL = "CONVERT_TO_PDF_OPEN_MODAL",
  CONVERT_TO_PDF_DOWNLOAD_IMAGE = "CONVERT_TO_PDF_DOWNLOAD_IMAGE",
  CONVERT_TO_PDF_DOWNLOAD_PDF = "CONVERT_TO_PDF_DOWNLOAD_PDF",
}
